apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: assets-inventory-service
  name: assets-inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assets-inventory-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: assets-inventory-service
    spec:
      containers:
      - image: localhost:5000/apps/demo
        name: assets-inventory-service
        resources: {}
status: {}
