apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: assets-inventory-service
  name: assets-inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assets-inventory-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: assets-inventory-service
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/service-meta-version: 'v1'
        consul.hashicorp.com/service-tags: 'api'
    spec:
      containers:
      - image: localhost:5000/apps/demo
        name: assets-inventory-service
        resources: {}
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
status: {}
