apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: assets-inventory-service
  name: assets-inventory-service
spec:
  type: LoadBalancer
  ports:
    - name: 80-8080
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: assets-inventory-service
status:
  loadBalancer: {}
